version: "3"

services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "drupal"
      POSTGRES_USER: ""
      POSTGRES_PASSWORD: ""
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - internal
      - external

  drupal:
    image: drupal:8.9-fpm-alpine
    container_name: drupal
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - internal
      - external
    volumes:
      - drupal-data:/var/www/html

  webserver:
    image: nginx:1.17.4-alpine
    container_name: webserver
    depends_on:
      - drupal
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - drupal-data:/var/www/html
      - static:/static
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - external

  postgres-wagtail:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "wagtail"
      POSTGRES_USER: ""
      POSTGRES_PASSWORD: ""
    networks:
      - external
      - internal

  wagtail_test:
    container_name: wagtail_test
    build: ./
    command: gunicorn wagtail_test.wsgi:application --bind 0.0.0.0:8000
    restart: unless-stopped
    depends_on:
      - postgres-wagtail
    expose:
      - 8000
    environment:
      - DJANGO_SETTINGS_MODULE=wagtail_test.settings.dev
    volumes:
      - static:/app/static
    networks:
      - external
      - internal

networks:
  external:
    driver: bridge
  internal:
    driver: bridge

volumes:
  drupal-data:
  db-data:
  static:
